# Generated by Django 3.0.8 on 2020-07-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing_listingcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingcategory',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='catergory',
        ),
        migrations.AddField(
            model_name='listing',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.ListingCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
