# Generated by Django 3.0.8 on 2020-07-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200709_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingcategory',
            options={},
        ),
    ]
