# Generated by Django 3.0.8 on 2020-07-09 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200709_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default=39, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category', to='auctions.ListingCategory'),
        ),
    ]
