# Generated by Django 3.0.8 on 2020-07-13 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
