# Generated by Django 3.0.8 on 2020-07-14 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comment_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default=39, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='listings', to='auctions.ListingCategory'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='wins', to=settings.AUTH_USER_MODEL),
        ),
    ]
